version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis

  web:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./server-entrypoint.sh
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/web/static/
      - media_value:/usr/share/nginx/html/web/media/
    depends_on:
      - redis
      - web

  celery:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./worker-entrypoint.sh
    restart: always
    volumes:
      - .:/app/celery
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./beat-entrypoint.sh
    restart: always
    volumes:
      - .:/app/celery_beat
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - celery



volumes:
  postgres_db:
  static_value:
  media_value:
